# -*- coding: utf-8 -*-
"""PROJECT (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hjVt8K6AdCOlhEMbzkwQT6qFQnoitFVh

##MACHINE LEARNING MODELS FOR SUSTAINABLE AGRICULTURE USING CROP RECOMMENDATION DATASET

##IMPORT NECESSARY LIBRARIES
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score, precision_score,recall_score,f1_score

"""##LOAD AND PREPROCESS THE DATASET"""

data = pd.read_csv("/content/Crop_recommendation (1).csv")
data.info()

print(data.columns)

data.head()

data.tail()

print(data.describe())

data.dtypes

print(data.isnull().sum())

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
data['label'] = label_encoder.fit_transform(data['label'])      # our 'label' is categorical text

"""##DATA VISUALIZATION

VISUALIZING FEATURE DISTRIBUTIONS

1.HISTOGRAM PLOT
"""

plt.figure(figsize=(12,8))
for i, column in enumerate(data.columns[:-1],1):
  plt.subplot(3,3,i)
  sns.histplot(data[column],kde=True)
  plt.title(f'Distribution of {column}')
  plt.show()

"""2.CORRELATION HEATMAP"""

plt.figure(figsize=(10,6))
sns.heatmap(data.corr(), annot = True, cmap = 'coolwarm')
plt.title('Correlation Heatmap')
plt.show()

"""SPLIT THE DATASET INTO FEATURES AND TARGET VARIABLES

1.SPLIT INTO FEATURES AND TARGET
"""

X = data.drop('label',axis = 1)
y = data['label']

"""2.SPLIT INTO TRAINING AND TESTING"""

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

"""3.STANDARDIZE THE FEATURES"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""##MODEL TRAINING WITH RANDOM FOREST CLASSIFIER

1.INITIALIZE AND TRAIN THE MODEL
"""

rf_model = RandomForestClassifier(random_state=42)
gb_model = RandomForestClassifier(random_state=42)

"""2.ENSEMBLE MODEL(VOTING CLASSIFIER)"""

ensemble_model = VotingClassifier(estimators=[('rf',rf_model),('gb',gb_model)],voting='soft')

"""3.Training ensemble model"""

ensemble_model.fit(X_train,y_train)

"""##HYPER PARAMETER TUNING

HYPER PARAMETER TUNING FOR RANDOMFOREST
"""

param_grid = {'n_estimators':[50,100,150],'max_depth':[10,20,30],'min_samples_split':[2,5,10]}
grid_search=GridSearchCV(estimator=rf_model,param_grid=param_grid,cv=5,scoring='accuracy')
grid_search.fit(X_train,y_train)

"""BEST PARAMETERS FOR RANDOM FOREST"""

best_rf_model = grid_search.best_estimator_

"""##EVALUATION METRICS

1.MAKE PREDICTION
"""

y_pred = ensemble_model.predict(X_test)

"""2.EVALUATION METRICS"""

accuracy = accuracy_score(y_test,y_pred)
precision = precision_score(y_test,y_pred, average = 'weighted')
recall = recall_score(y_test,y_pred, average = 'weighted')
f1 = f1_score(y_test,y_pred, average = 'weighted')

print("Ensemble Model Evaluation Metrics:")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

"""##FUTURE APPLICATIONS SAVE THE MODEL

SAVE THE MODEL FOR FUTURE USE
"""

import joblib
import pickle
from flask import Flask,request,jsonify,render_template
from sklearn.preprocessing import StandardScaler

joblib.dump(ensemble_model,'/content/crop_recommendation_model.pkl')
print("Model saved for future applications")

"""## REAL TIME PREDICTION

1.LOAD THE MODEL
"""

loaded_model = joblib.load('/content/crop_recommendation_model.pkl')
joblib.dump(scaler, '/content/scaler.pkl')
joblib.dump(label_encoder, '/content/scaler.pkl')
print('Model loaded successfully')

"""2.GET INPUT FROM USERS"""

Nitrogen = int(input("Enter the nitrogen level: "))
Phosphorus = int(input("Enter the phosphorus level: "))
Pottassium = int(input("Enter the pottassium level: "))
Temperature = float(input("Enter the temperature level: "))
Humidity = float(input("Enter the humidity level: "))
pH = float(input("Enter the pH level: "))
Rainfall = float(input("Enter the rainfall level: "))

new_data = [[Nitrogen,Phosphorus,Pottassium,Temperature,Humidity,pH,Rainfall]]

new_data_scaled = scaler.transform(new_data)

predicted_label = loaded_model.predict(new_data_scaled)
predicted_label_name = label_encoder.inverse_transform(predicted_label)

print("Recommendad Crop:" ,predicted_label_name[0])

